### ISSUE TITLE
Is it Python 3.2 Compatible ?

### ISSUE THREAD

**Issue by nuummi** [tungwaiyip/HTMLTestRunner#1]
Hello Wai Yip,
I'm using your module and it's working great!!
Recently I was trying to use an earlier version of HTMLTestRunner in Python 3.2, but it could not run. Is the new version (0.8.2) compatible for Python 3.2 ?

Thanks!
Noam.

**Comment by tungwaiyip** [comment]
Good question. HTMLTestRunner date back to 2005 and has not been ported to Python 3. This is an excellent request to work on. Unicode handling was a mess back in the old days (Python 2.4?). I am looking forward for easier time in Python 3.

**Comment by alain1** [comment]
hi
 has this been updated to run with the latest version of python?

**Comment by tungwaiyip** [comment]
No it have not been updated in a long time.

**Comment by kaphola** [comment]
Hi Wai,

I was using your module HTMLTestRunner.py for generating report with selenium 2.35.0 and python 2.7 and it was working fine.

Now i upgraded python 2 to python 3 and selenium 2.35.0 to selenium 2.43.0, now i am able to run my test cases but it is not generating report.

Kindly let me know have you added support for python 3.

Thanks,
Ajay

**Comment by SulakshnaDas** [comment]
Hi Wai,
I am using HTMLTestRunner.py for generating report with python2.6 and it is working fine but now I am upgrading python 2.6 to python 3.4.So Do you have any update on HTMLTestRunner compatible to python 3.4?

Thanks,
Sulakshna

**Comment by tungwaiyip** [comment]
I'm not able to spend any time on this project. If anyone can kindly continue the development it will be much appreciated.

**Comment by ElaineAng** [comment]
I made some small changes to your project and it now works for me (with python 3.4), although probably the changes are not decent enough.
Thank you so much for your work!

**Comment by SulakshnaDas** [comment]
@ElaineAng Could you please tell me about changes that you made in this module which worked for you.It would be of great help to me.
Thanks,
Sulakshna

**Comment by ElaineAng** [comment]
@SulakshnaDas Hi, sorry for the late reply. I am a beginner on python so I don't know whether the changes I made is decent. I was using code from his website, which seems to have slight (and unimportant) difference from the code in the github here. website URL: http://tungwaiyip.info/software/HTMLTestRunner_0_8_2/HTMLTestRunner.py

The changes that I made:

Line 94: from io import *

Line 538, in method startTest(self,test): self.outputBuffer=StringIO()

Line 631, in method run(self,test): print ("\nTime Elapsed: %s" %(self.stopTime-self.startTime), \
                                                       file=sys.stderr)

In method _generate_report_test(self,rows,cid,tid,n,t,o,e):
Line 766: uo=o
Line 768: uo=o.decode()
Line 772: ue=e
Line 774: ue=e.decode()

Hopefully it helps...

**Comment by locus2k** [comment]
In 3.x it is no longer StringIO.

Here are the changes that I made to get it to work for 3.4

Line 94: import io as StringIO

Line 63: print('Time Elapsed: {}'.format((self.stopTime-self.startTime)), file=sys.stderr)

in the methoid __generate_report_test: change all the decodes to: uo = bytes(o, 'utf-8').decode('latin-1') (or ue and e)

**Comment by maulikthaker** [comment]
Correction from above : Itls line 632.
Insert this in line 692 : `self.stream.write(output)`
Insert this in line 644 : `if not cls in rmap.keys:`

**Comment by KimzNz** [comment]
to work with 3.x

"""
A TestRunner for use with the Python unit testing framework. It
generates a HTML report to show the result at a glance.

The simplest way to use this is to invoke its main method. E.g.

```
import unittest
import HTMLTestRunner

... define your tests ...

if __name__ == '__main__':
    HTMLTestRunner.main()
```

For more customization options, instantiates a HTMLTestRunner object.
HTMLTestRunner is a counterpart to unittest's TextTestRunner. E.g.

```
# output to a file
fp = file('my_report.html', 'wb')
runner = HTMLTestRunner.HTMLTestRunner(
            stream=fp,
            title='My unit test',
            description='This demonstrates the report output by HTMLTestRunner.'
            )

# Use an external stylesheet.
# See the Template_mixin class for more customizable options
runner.STYLESHEET_TMPL = '<link rel="stylesheet" href="my_stylesheet.css" type="text/css">'

# run the test
runner.run(my_test_suite)
```

---

Copyright (c) 2004-2007, Wai Yip Tung
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:
- Redistributions of source code must retain the above copyright notice,
  this list of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.
- Neither the name Wai Yip Tung nor the names of its contributors may be
  used to endorse or promote products derived from this software without
  specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

# URL: http://tungwaiyip.info/software/HTMLTestRunner.html

**author** = "Wai Yip Tung"
**version** = "0.8.2"

"""
Change History

Version 0.8.2
- Show output inline instead of popup window (Viorel Lupu).

Version in 0.8.1
- Validated XHTML (Wolfgang Borgert).
- Added description of test classes and test cases.

Version in 0.8.0
- Define Template_mixin class for customization.
- Workaround a IE 6 bug that it does not treat <script> block as CDATA.

Version in 0.7.1
- Back port to Python 2.3 (Frank Horowitz).
- Fix missing scroll bars in detail log (Podi).
  """

# TODO: color stderr

# TODO: simplify javascript using ,ore than 1 class in the class attribute?

import datetime
import sys
import time
import unittest
from xml.sax import saxutils
from io import StringIO

# ------------------------------------------------------------------------

# The redirectors below are used to capture output during testing. Output

# sent to sys.stdout and sys.stderr are automatically captured. However

# in some cases sys.stdout is already cached before HTMLTestRunner is

# invoked (e.g. calling logging.basicConfig). In order to capture those

# output, use the redirectors for the cached stream.

#

# e.g.

# >>> logging.basicConfig(stream=HTMLTestRunner.stdout_redirector)

# >>>

class OutputRedirector(object):
    """ Wrapper to redirect stdout or stderr """
    def **init**(self, fp):
        self.fp = fp

```
def write(self, s):
    self.fp.write(s)

def writelines(self, lines):
    self.fp.writelines(lines)

def flush(self):
    self.fp.flush()
```

stdout_redirector = OutputRedirector(sys.stdout)
stderr_redirector = OutputRedirector(sys.stderr)

# ----------------------------------------------------------------------

# Template

class Template_mixin(object):
    """
    Define a HTML template for report customerization and generation.

```
Overall structure of an HTML report

HTML
+------------------------+
|<html>                  |
|  <head>                |
|                        |
|   STYLESHEET           |
|   +----------------+   |
|   |                |   |
|   +----------------+   |
|                        |
|  </head>               |
|                        |
|  <body>                |
|                        |
|   HEADING              |
|   +----------------+   |
|   |                |   |
|   +----------------+   |
|                        |
|   REPORT               |
|   +----------------+   |
|   |                |   |
|   +----------------+   |
|                        |
|   ENDING               |
|   +----------------+   |
|   |                |   |
|   +----------------+   |
|                        |
|  </body>               |
|</html>                 |
+------------------------+
"""

STATUS = {
0: 'pass',
1: 'fail',
2: 'error',
}

DEFAULT_TITLE = 'Unit Test Report'
DEFAULT_DESCRIPTION = ''

# ------------------------------------------------------------------------
# HTML Template

HTML_TMPL = r"""<?xml version="1.0" encoding="UTF-8"?>
```

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>%(title)s</title>
    <meta name="generator" content="%(generator)s"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    %(stylesheet)s
</head>
<body>

<script language="javascript" type="text/javascript"></script>

%(heading)s
%(report)s
%(ending)s

</body>
</html>
"""
    # variables: (title, generator, stylesheet, heading, report, ending)

```
# ------------------------------------------------------------------------
# Stylesheet
#
# alternatively use a <link> for external style sheet, e.g.
#   <link rel="stylesheet" href="$url" type="text/css">

STYLESHEET_TMPL = """
```

<style type="text/css" media="screen">
body        { font-family: verdana, arial, helvetica, sans-serif; font-size: 80%; }
table       { font-size: 100%; }
pre         { }
/* -- heading ---------------------------------------------------------------------- */
h1 {
    font-size: 16pt;
    color: gray;
}
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .attribute {
    margin-top: 1ex;
    margin-bottom: 0;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- css div popup ------------------------------------------------------------------------ */
a.popup_link {
}
a.popup_link:hover {
    color: red;
}
.popup_window {
    display: none;
    position: relative;
    left: 0px;
    top: 0px;
    /*border: solid #627173 1px; */
    /*padding: 10px; */
    background-color: #E6E6D6;
    font-family: "Lucida Console", "Courier New", Courier, monospace;
    text-align: left;
    font-size: 8pt;
    /*width: 500px;*/
}
}
/* -- report ------------------------------------------------------------------------ */
#show_detail_line {
    margin-top: 3ex;
    margin-bottom: 1ex;
}
#result_table {
    width: 80%;
    border-collapse: collapse;
    border: 1px solid #777;
}
#header_row {
    font-weight: bold;
    color: white;
    background-color: #777;
}
#result_table td {
    border: 1px solid #777;
    padding: 2px;
}
#total_row  { font-weight: bold; }
.passClass  { background-color: #6c6; }
.failClass  { background-color: #c60; }
.errorClass { background-color: #c00; }
.passCase   { color: #6c6; }
.failCase   { color: #c60; font-weight: bold; }
.errorCase  { color: #c00; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
/* -- ending ---------------------------------------------------------------------- */
#ending {
}
</style>

"""

```
# ------------------------------------------------------------------------
# Heading
#

HEADING_TMPL = """<div class='heading'>
```

<h1>%(title)s</h1>

%(parameters)s

<p class='description'>%(description)s</p>

</div>

""" # variables: (title, parameters, description)

```
HEADING_ATTRIBUTE_TMPL = """<p class='attribute'><strong>%(name)s:</strong> %(value)s</p>
```

""" # variables: (name, value)

```
# ------------------------------------------------------------------------
# Report
#

REPORT_TMPL = """
```

<p id='show_detail_line'>Show
<a href='javascript:showCase(0)'>Summary</a>
<a href='javascript:showCase(1)'>Failed</a>
<a href='javascript:showCase(2)'>All</a>
</p>

<table id='result_table'>
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row'>
    <td>Test Group/Test case</td>
    <td>Count</td>
    <td>Pass</td>
    <td>Fail</td>
    <td>Error</td>
    <td>View</td>
</tr>
%(test_list)s
<tr id='total_row'>
    <td>Total</td>
    <td>%(count)s</td>
    <td>%(Pass)s</td>
    <td>%(fail)s</td>
    <td>%(error)s</td>
    <td>&nbsp;</td>
</tr>
</table>

""" # variables: (test_list, count, Pass, fail, error)

```
REPORT_CLASS_TMPL = r"""
```

<tr class='%(style)s'>
    <td>%(desc)s</td>
    <td>%(count)s</td>
    <td>%(Pass)s</td>
    <td>%(fail)s</td>
    <td>%(error)s</td>
    <td><a href="javascript:showClassDetail('%(cid)s',%(count)s)">Detail</a></td>
</tr>
""" # variables: (style, desc, count, Pass, fail, error, cid)

```
REPORT_TEST_WITH_OUTPUT_TMPL = r"""
```

<tr id='%(tid)s' class='%(Class)s'>
    <td class='%(style)s'><div class='testcase'>%(desc)s</div></td>
    <td colspan='5' align='center'>

```
<!--css div popup start-->
<a class="popup_link" onfocus='this.blur();' href="javascript:showTestDetail('div_%(tid)s')" >
    %(status)s</a>

<div id='div_%(tid)s' class="popup_window">
    <div style='text-align: right; color:red;cursor:pointer'>
    <a onfocus='this.blur();' onclick="document.getElementById('div_%(tid)s').style.display = 'none' " >
       [x]</a>
    </div>
    <pre>
    %(script)s
    </pre>
</div>
<!--css div popup end-->

</td>
```

</tr>
""" # variables: (tid, Class, style, desc, status)

```
REPORT_TEST_NO_OUTPUT_TMPL = r"""
```

<tr id='%(tid)s' class='%(Class)s'>
    <td class='%(style)s'><div class='testcase'>%(desc)s</div></td>
    <td colspan='5' align='center'>%(status)s</td>
</tr>
""" # variables: (tid, Class, style, desc, status)

```
REPORT_TEST_OUTPUT_TMPL = r"""
```

%(id)s: %(output)s
""" # variables: (id, output)

```
# ------------------------------------------------------------------------
# ENDING
#

ENDING_TMPL = """<div id='ending'>&nbsp;</div>"""
```

# -------------------- The end of the Template class -------------------

TestResult = unittest.TestResult

class _TestResult(TestResult):
    # note: _TestResult is a pure representation of results.
    # It lacks the output and reporting ability compares to unittest._TextTestResult.

```
def __init__(self, verbosity=1):
    TestResult.__init__(self)
    self.stdout0 = None
    self.stderr0 = None
    self.success_count = 0
    self.failure_count = 0
    self.error_count = 0
    self.verbosity = verbosity

    # result is a list of result in 4 tuple
    # (
    #   result code (0: success; 1: fail; 2: error),
    #   TestCase object,
    #   Test output (byte string),
    #   stack trace,
    # )
    self.result = []

def startTest(self, test):
    TestResult.startTest(self, test)
    # just one buffer for both stdout and stderr
    self.outputBuffer = StringIO()
    stdout_redirector.fp = self.outputBuffer
    stderr_redirector.fp = self.outputBuffer
    self.stdout0 = sys.stdout
    self.stderr0 = sys.stderr
    sys.stdout = stdout_redirector
    sys.stderr = stderr_redirector


def complete_output(self):
    """
    Disconnect output redirection and return buffer.
    Safe to call multiple times.
    """
    if self.stdout0:
        sys.stdout = self.stdout0
        sys.stderr = self.stderr0
        self.stdout0 = None
        self.stderr0 = None
    return self.outputBuffer.getvalue()


def stopTest(self, test):
    # Usually one of addSuccess, addError or addFailure would have been called.
    # But there are some path in unittest that would bypass this.
    # We must disconnect stdout in stopTest(), which is guaranteed to be called.
    self.complete_output()


def addSuccess(self, test):
    self.success_count += 1
    TestResult.addSuccess(self, test)
    output = self.complete_output()
    self.result.append((0, test, output, ''))
    if self.verbosity > 1:
        sys.stderr.write('ok ')
        sys.stderr.write(str(test))
        sys.stderr.write('\n')
    else:
        sys.stderr.write('.')

def addError(self, test, err):
    self.error_count += 1
    TestResult.addError(self, test, err)
    _, _exc_str = self.errors[-1]
    output = self.complete_output()
    self.result.append((2, test, output, _exc_str))
    if self.verbosity > 1:
        sys.stderr.write('E  ')
        sys.stderr.write(str(test))
        sys.stderr.write('\n')
    else:
        sys.stderr.write('E')

def addFailure(self, test, err):
    self.failure_count += 1
    TestResult.addFailure(self, test, err)
    _, _exc_str = self.failures[-1]
    output = self.complete_output()
    self.result.append((1, test, output, _exc_str))
    if self.verbosity > 1:
        sys.stderr.write('F  ')
        sys.stderr.write(str(test))
        sys.stderr.write('\n')
    else:
        sys.stderr.write('F')
```

class HTMLTestRunner(Template_mixin):
    """
    """
    def **init**(self, stream=sys.stdout, verbosity=1, title=None, description=None):
        self.stream = stream
        self.verbosity = verbosity
        if title is None:
            self.title = self.DEFAULT_TITLE
        else:
            self.title = title
        if description is None:
            self.description = self.DEFAULT_DESCRIPTION
        else:
            self.description = description

```
    self.startTime = datetime.datetime.now()


def run(self, test):
    " Run the given test case or test suite."
    result = _TestResult(self.verbosity)
    test(result)
    self.stopTime = datetime.datetime.now()
    self.generateReport(test, result)
    # timelapse = self.stopTime-self.startTime
    # print('Time Elapsed: ' + '%s:' % timelapse)
    return result


def sortResult(self, result_list):
    # unittest does not seems to run in any particular order.
    # Here at least we want to group them together by class.
    rmap = {}
    classes = []
    for n,t,o,e in result_list:
        cls = t.__class__
        if cls not in rmap.keys():
            rmap[cls] = []
            classes.append(cls)
        rmap[cls].append((n,t,o,e))
    r = [(cls, rmap[cls]) for cls in classes]
    return r


def getReportAttributes(self, result):
    """
    Return report attributes as a list of (name, value).
    Override this to add custom attributes.
    """
    startTime = str(self.startTime)[:19]
    duration = str(self.stopTime - self.startTime)
    status = []
    if result.success_count: status.append('Pass %s'    % result.success_count)
    if result.failure_count: status.append('Failure %s' % result.failure_count)
    if result.error_count:   status.append('Error %s'   % result.error_count  )
    if status:
        status = ' '.join(status)
    else:
        status = 'none'
    return [
        ('Start Time', startTime),
        ('Duration', duration),
        ('Status', status),
    ]


def generateReport(self, test, result):
    report_attrs = self.getReportAttributes(result)
    generator = 'HTMLTestRunner %s' % __version__
    stylesheet = self._generate_stylesheet()
    heading = self._generate_heading(report_attrs)
    report = self._generate_report(result)
    ending = self._generate_ending()
    output = self.HTML_TMPL % dict(
        title = saxutils.escape(self.title),
        generator = generator,
        stylesheet = stylesheet,
        heading = heading,
        report = report,
        ending = ending,
    )
    self.stream.write(output)


def _generate_stylesheet(self):
    return self.STYLESHEET_TMPL


def _generate_heading(self, report_attrs):
    a_lines = []
    for name, value in report_attrs:
        line = self.HEADING_ATTRIBUTE_TMPL % dict(
                name = saxutils.escape(name),
                value = saxutils.escape(value),
            )
        a_lines.append(line)
    heading = self.HEADING_TMPL % dict(
        title = saxutils.escape(self.title),
        parameters = ''.join(a_lines),
        description = saxutils.escape(self.description),
    )
    return heading


def _generate_report(self, result):
    rows = []
    sortedResult = self.sortResult(result.result)
    for cid, (cls, cls_results) in enumerate(sortedResult):
        # subtotal for a class
        np = nf = ne = 0
        for n,t,o,e in cls_results:
            if n == 0: np += 1
            elif n == 1: nf += 1
            else: ne += 1

        # format class description
        if cls.__module__ == "__main__":
            name = cls.__name__
        else:
            name = "%s.%s" % (cls.__module__, cls.__name__)
        doc = cls.__doc__ and cls.__doc__.split("\n")[0] or ""
        desc = doc and '%s: %s' % (name, doc) or name

        row = self.REPORT_CLASS_TMPL % dict(
            style = ne > 0 and 'errorClass' or nf > 0 and 'failClass' or 'passClass',
            desc = desc,
            count = np+nf+ne,
            Pass = np,
            fail = nf,
            error = ne,
            cid = 'c%s' % (cid+1),
        )
        rows.append(row)

        for tid, (n,t,o,e) in enumerate(cls_results):
            self._generate_report_test(rows, cid, tid, n, t, o, e)

    report = self.REPORT_TMPL % dict(
        test_list = ''.join(rows),
        count = str(result.success_count+result.failure_count+result.error_count),
        Pass = str(result.success_count),
        fail = str(result.failure_count),
        error = str(result.error_count),
    )
    return report


def _generate_report_test(self, rows, cid, tid, n, t, o, e):
    # e.g. 'pt1.1', 'ft1.1', etc
    has_output = bool(o or e)
    tid = (n == 0 and 'p' or 'f') + 't%s.%s' % (cid+1,tid+1)
    name = t.id().split('.')[-1]
    doc = t.shortDescription() or ""
    desc = doc and ('%s: %s' % (name, doc)) or name
    tmpl = has_output and self.REPORT_TEST_WITH_OUTPUT_TMPL or self.REPORT_TEST_NO_OUTPUT_TMPL

    # o and e should be byte string because they are collected from stdout and stderr?
    if isinstance(o, str):
        # TODO: some problem with 'string_escape': it escape \n and mess up formating
        uo = o.encode('utf-8')
        uo = uo.decode('utf-8')
    else:
        uo = o
    if isinstance(e, str):
        # TODO: some problem with 'string_escape': it escape \n and mess up formating
        ue = e.encode('utf-8')
        ue = ue.decode('utf-8')
    else:
        ue = e

    script = self.REPORT_TEST_OUTPUT_TMPL % dict(
        id = tid,
        output = saxutils.escape(uo+ue),
    )

    row = tmpl % dict(
        tid = tid,
        Class = (n == 0 and 'hiddenRow' or 'none'),
        style = n == 2 and 'errorCase' or (n == 1 and 'failCase' or 'none'),
        desc = desc,
        script = script,
        status = self.STATUS[n],
    )
    rows.append(row)
    if not has_output:
        return

def _generate_ending(self):
    return self.ENDING_TMPL
```

##############################################################################

# Facilities for running tests from the command line

##############################################################################

# Note: Reuse unittest.TestProgram to launch test. In the future we may

# build our own launcher to support more specific command line

# parameters like test title, CSS, etc.

class TestProgram(unittest.TestProgram):
    """
    A variation of the unittest.TestProgram. Please refer to the base
    class for command line parameters.
    """
    def runTests(self):
        # Pick HTMLTestRunner as the default test runner.
        # base class's testRunner parameter is not useful because it means
        # we have to instantiate HTMLTestRunner before we know self.verbosity.
        if self.testRunner is None:
            self.testRunner = HTMLTestRunner(verbosity=self.verbosity)
        unittest.TestProgram.runTests(self)

main = TestProgram

##############################################################################

# Executing this module from the command line

##############################################################################

if **name** == "**main**":
    main(module=None)

**Comment by dash0002** [comment]
You may want to use the fork available at https://github.com/dash0002/HTMLTestRunner which is ready for Python 3.

**Comment by dheerajalim** [comment]
You can use the fork https://github.com/dheerajalim/HTMLTestRunner
This is compatible with Python 3 - 3.5.1

**Comment by Akopov4** [comment]
hI, none of these solutions work with python 3.5.2 . If I used solution of   @dheerajalim I have got such errors:
  ```
File "/home/akop/py_workspace/setest/2/smoketests_with_html_report.py", line 26, in <module>
    runner.run(smoke_tests)
  File "/home/akop/py_workspace/setest/2/HTMLTestRunner.py", line 562, in run
    self.generateReport(test, result)
  File "/home/akop/py_workspace/setest/2/HTMLTestRunner.py", line 619, in generateReport
    self.stream.write(output.encode('utf8'))
TypeError: write() argument must be str, not bytes
```
If I used solution of @dash0002 I got such errors:
```
/usr/bin/python3.5 /home/akop/py_workspace/setest/2/smoketests_with_html_report.py
.....Traceback (most recent call last):
  File "/home/akop/py_workspace/setest/2/smoketests_with_html_report.py", line 26, in <module>
    runner.run(smoke_tests)
  File "/home/akop/py_workspace/setest/2/HTMLTestRunner.py", line 538, in run
    self.generateReport(test, result)
  File "/home/akop/py_workspace/setest/2/HTMLTestRunner.py", line 586, in generateReport
    report = self._generate_report(result)
  File "/home/akop/py_workspace/setest/2/HTMLTestRunner.py", line 646, in _generate_report
    cid = 'c%s' % (cid+1),
KeyError: 'skip'
```

**Comment by dash0002** [comment]
Quick double check @Akopov4; With the version available from @dheerajalim or @dash0002 it works in 3.5.1, but in 3.5.2 you receive this error?

**Comment by dheerajalim** [comment]
Hi Akop,

It says
TypeError: write() argument must be str, not bytes

Can you try changing 'wb' to 'w'.

That should solve this!

**Comment by Akopov4** [comment]
@dash0002 yes it appears in 3.5.2. @dheerajalim unclear- please explain

**Comment by hasanibnmansoor** [comment]
@Akopov4 I tried this and it worked.
outfile = open(dir + "\SmokeTestReport.html", "wb")
In code to open the file, give 'wb' instead of 'w' and it should work. It worked for me.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Summarizing the changes, following changes to the original HTMLTestRunner file would get things work:
1. import StringIO to import io as StringIO
2. Change the print statement in Line 630 to **print('Time Elapsed: {}'.format((self.stopTime-self.startTime)), file=sys.stderr)**
3. Change the **if not rmap.has_key(cls)** in Line 642 to **if cls not in rmap:**
4. In the Python Code to Open the File (Your testing code, not HTMLTestRunner.py), update the code to open the report file to have **"wb" instead of "w"**
**# open the report file
outfile = open(dir + "\SmokeTestReport.html", "wb")**
5. Change the decoding statement in line 766 and 772 to **uo = bytes(o, 'utf-8').decode('latin-1')** and **ue = bytes(e, 'utf-8').decode('latin-1')** respectively.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Above steps got me working in Python 3.6

**Comment by dash0002** [comment]
@Akopov4 I'd be very happy to accept a pull request for this change at https://github.com/dash0002/HTMLTestRunner (which should be 3 compatible branch).

**Comment by tjtripp** [comment]
I've just confirmed that this package works: https://github.com/oldani/HtmlTestRunner 
Just download the .whl file from PyPI and install from console.

**Comment by bobwassell** [comment]
This works well.
https://programming.vip/docs/python-3.x-install-htmltestrunner-and-use.html
tested in 3.9
